### ISSUE TITLE
 lalsuite and  PyCBC 

### ISSUE THREAD

**Issue by Fccczj** [timothygebhard/ggwd#3]
Hello, I have an issue while trying to run it. I am unable to install lalsuite=6.53 and PyCBC=1.13.6 in the Python 2.7 environment. Can you please help me with this? Thank you.

**Comment by timothygebhard** [comment]
Yes, it seems that `lalsuite` is no longer providing versions on PyPI that are not Python 3-compatible.

For what it's worth, I did my own reproducibility test a few months ago, and managed to get the `ggwd` code to work with Python 3 (using the latest versions of `lalsuite` and `PyCBC`, respectively) with just a few minor tweaks. I have pushed this version to a separate branch (called `python3`) — feel free to check it out and see if it helps with your problem. I provide this as is, with no guarantees. Also, please note that the code in this repository is generally no longer actively maintained, as I am no longer working on gravitational waves.

**Comment by Fccczj** [comment]
> 是的，似乎不再在 PyPI 上提供与 Python 3 不兼容的版本。`lalsuite`
> 
> 值得一提的是，几个月前，我做了自己的可重复性测试，并设法让代码与 Python 3 一起使用（分别使用最新版本的 和 ），只需进行一些小的调整。我已将此版本推送到一个单独的分支（称为 ） - 请随时检查它，看看它是否有助于解决您的问题。我按原样提供，不作任何保证。另外，请注意，由于我不再研究引力波，因此此存储库中的代码通常不再被积极维护。`ggwd``lalsuite``PyCBC``python3`

Thank you very much for your guidance. Wishing you all the best!
